### ISSUE TITLE
Swiping is broken since update to 1.97.5

### ISSUE THREAD

**Issue by CaptainTyphoo** [nilsbraden/ttrss-reader-fork#475] opened 2024-09-23 19:28 UTC
Since the update from 1.97.4 to 1.97.5 swiping works only in one direction.

Steps to reproduce:
1. open a feed
2. open an article
3. swipe to left/right

actual result:
ttrss-reader moves always "upwards" in the feed no matter if I swipe left or right

expected result:
swipe left, ttrss-reader moves down
swipe right, ttrss-reader moved up

Additional info:
If I tilt my phone sideways so it is in landscape mode, it works the other way around. Swiping left or right will only move ttrss-reader "downwards" in the feed.

Seen on a Pixel 4a with GrapheneOS (Android 13)

**Comment by nilsbraden** [comment] 2024-09-25 14:40
Duplicate of #474

**Closed** 2024-09-25 14:40 UTC
