### ISSUE TITLE
self-signed certificate no longer working with v1.93

### ISSUE THREAD

**Issue by holtrop** [nilsbraden/ttrss-reader-fork#375] opened 2018-03-20 13:00 UTC
I have a self-signed certificate for my server. Unfortunately I can't use Let's Encrypt because I'm using a dynamic DNS subdomain. With version 1.92 connecting to my server with my self-signed certificate worked fine using the same settings displayed in #354 . With v1.93 I can no longer connect. I downloaded v1.92 APK and manually installed to verify that it still works and it does.

I am on Android 6.0.

**Comment by nilsbraden** [comment] 2018-03-24 11:26
Probably a duplicate of #376

**Closed by nilsbraden** 2018-03-24 11:26 UTC
