### ISSUE TITLE
SSL Error with letsencrypt certificate

### ISSUE THREAD

**Issue by tautologe** [nilsbraden/ttrss-reader-fork#313] opened 2015-12-28 14:30 UTC
Hi,
After letsencrypt being publically available I wanted to switch from my self-signed certificate to a letsencrypt-signed certificate, to get rid of the need to install the CA manually to the system.

I heard that Android 4.4.4 is ready for letsecrypt, but the TTRSS-Reader does not seem to know the letsencrypt certificate. I get the error message "SSLException in doRequest(): java.security.cert.CertPathValidatorException: Trust anchor for certification path not found." 

This error occurs on my Android 4.4.4 (with Cyanogenmod 11) device as well as on my Android 6.0.1 device.

**Comment by loomy** [comment] 2016-02-04 20:38
Same here. Is there some progress on this?

**Comment by nilsbraden** [comment] 2016-02-13 21:21
Duplicate of #312, please move over there...

**Closed by nilsbraden** 2016-02-13 21:21 UTC

**Comment by tautologe** [comment] 2016-05-04 15:18
It does not seem to be a duplicate. #312 is about self signed certificates. I would like TTRSS-Reader to accept lets-encrypt-signed certificates without the need to install the certificate manually.
